apiVersion: v1
kind: Pod
metadata:
  name: back-end-pod
  labels:
    name: back-end-pod
    app: demo-multi-tier

spec: 
  containers:
  - name: redis
    image: redis
    ports:
    - containerport: 6379
 
